site_name: SoulLanguage
site_url: https://owner.github.io/SoulLanguage/
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
markdown_extensions:
  - admonition
  - pymdownx.superfences
nav:
  - Home: index.md
  - Tutorial:
      - Hello Glyph: tutorial/hello_glyph.md
      - REPL Guide: tutorial/repl.md
  - Reference:
      - SIL: reference/sil.md
      - SQLy: reference/sqly.md
