name: Release

on:
  push:
    tags:
      - 'sqly-v1.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          pip install pip-tools
          pip-sync requirements/dev.txt
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build
